name: basketball

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: matt-ball/newman-action@master
      with:
        collection: basketball.postman_collection.json
        envVar: '[{ "key": "baseUrl", "value": "https://v1.basketball.api-sports.io" },
                  { "key": "api-key", "value": "${{ secrets.basketballApiKey }}" }]'
